{% set name = "cwinpy" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f78df4926f76b50f6c1b27985a57844a6139e86a34f8dbd7fdf6564e6d6c16c1

build:
  entry_points:
    - cwinpy_knope = cwinpy.knope.knope:knope_cli
    - cwinpy_knope_dag = cwinpy.knope.knope:knope_dag_cli
    - cwinpy_knope_generate_pp_plots = cwinpy.knope.testing:generate_pp_plots
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - astropy
    - bilby >=0.5.8
    - bilby_pipe >=0.2.0
    - gwpy
    - lintegrate
    - matplotlib-base
    - numba
    - numpy >=1.15
    - pycondor
    - python >=3.6
    - python-lal
    - python-lalpulsar
    - scipy

test:
  imports:
    - cwinpy
  commands:
    - cwinpy_knope --help
    - cwinpy_knope_dag --help
    - cwinpy_knope_generate_pp_plots --help

about:
  home: https://github.com/cwinpy/cwinpy/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: CW Inference in Python
  doc_url: https://cwinpy.readthedocs.io/en/latest/
  dev_url: https://github.com/cwinpy/cwinpy/
  description: |
    A Python module for performing Bayesian inference for continuous gravitational-wave signals from pulsars.

extra:
  recipe-maintainers:
    - mattpitkin
    - duncanmmacleod
